services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - queue_storage:/app/shared_queue_dir
    environment:
      - FLASK_ENV=development
    networks:
      - scraper-21277-21219

  engine:
    build:
      context: .
      dockerfile: Dockerfile 
    command: python /app/engine/engine.py
    depends_on:
      - mongo
    volumes:
      - queue_storage:/app/shared_queue_dir
    networks:
      - scraper-21277-21219

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - scraper-21277-21219

networks:
  scraper-21277-21219:
    driver: bridge

volumes:
  mongo-data:
  queue_storage: